IATI/validator-services

.dockerignore, .funcignore, .github/workflows/develop-func-deploy.yml, Dockerfile
[Trello](https://trello.com/c/AEVr9zp8)﻿
=> Dockerise deployment

.github/workflows/develop-func-deploy.yml, .github/workflows/prod-func-deploy.yml
- Dockerise deployment for PRD
=> Next Release

.github/workflows/develop-func-deploy.yml, .github/workflows/prod-func-deploy.yml
[Trello](https://trello.com/c/KaQzR98d)﻿
=> update to use KV URI instead of KV name for v4 function

README.md, database/db.js, integration-tests/validator-services-tests.postman_collection.json, pvt-get-publishers-flagged/function.json, pvt-get-publishers-flagged/index.js
[Trello](https://trello.com/c/ahapvH5r)
- add black flagged publishers endpoint
- remove unused db function
- add document for black flagged publishers route
=> Flagged Publisher Route

database/db.js, integration-tests/validator-services-tests.postman_collection.json
[Trello](https://trello.com/c/Y7IdQENb)
=> add alv_start and alv_error to documents routes

database/db.js, integration-tests/validator-services-tests.postman_collection.json
[Trello](https://trello.com/c/WHKck0on)
=> add solrize_end to single document endpoint response

README.md, database/db.js
[Trello](https://trello.com/c/5wG5qk9d)
=> update regenerate validation report routes for Activity level validation

database/db.js
[Trello](https://trello.com/c/HQau2ROQ)
=> use new alv_revalidate flag for revalidation of critical files

database/db.js
[Trello](https://trello.com/c/HQau2ROQ)
=> handle re-validate for errored alv files

.github/workflows/prod-func-deploy.yml
[Trello](https://trello.com/c/C7ND3XM0)
[Wiki](https://github.com/IATI/IATI-Internal-Wiki/blob/main/Technical-Climate-Impact/Measurement.md)
=> add tags for Prod

integration-tests/validator-services-tests.postman_collection.json
[Trello](https://trello.com/c/4DeA8Mvo)
=> update integration tests for adhoc guid update

.github/workflows/develop-func-deploy.yml
[Trello](https://trello.com/c/avaMLm6I)
=> deploy to consumption function

integration-tests/validator-services-tests.postman_collection.json
[Trello](https://trello.com/c/ihOOOhtB)
=> fix adhoc integration tests so they wait for blob trigger dynamically

.github/workflows/develop-func-deploy.yml, .github/workflows/prod-func-deploy.yml
[Trello](https://trello.com/c/avaMLm6I)
=> remove TCI tags after move to consumption function

.eslintrc.json, blob-trigger-adhoc-file/index.js, config/config.js, database/db.js, package-lock.json, package.json, pub-get-report/index.js, pub-get-stats-all/index.js, pub-get-stats-publisher/index.js, pub-get-stats-summary-aggregate/index.js, pub-get-stats-summary-precalc/index.js, pub-get-version/index.js, pvt-get-adhoc-session/index.js, pvt-get-guidance-links/index.js, pvt-get-publishers-documents/index.js, pvt-get-publishers-flagged/index.js, pvt-get-publishers/index.js, pvt-get-single-document/index.js, pvt-get-single-publisher/index.js, pvt-patch-validation-regenerate-all/index.js, pvt-patch-validation-regenerate/index.js, pvt-post-adhoc-file/index.js, pvt-post-adhoc-url/index.js, utils/utils.js
[Trello](https://trello.com/c/BxZPOEmp)
=> migrate to ecmascript modules

.gitignore, README.md, database/db.js, docs/validationReport.schema.json, integration-tests/validator-services-tests.postman_collection.json, pub-get-report/index.js
[Trello](https://trello.com/c/RuSXMIHw)
=> Add functionality around document name as defined by the registry

README.md, database/db.js, integration-tests/validator-services-tests.postman_collection.json, pvt-get-single-document/function.json, pvt-get-single-document/index.js
[Trello](https://trello.com/c/SPxWrwoh)
=> allow for document lookup by name

integration-tests/validator-services-tests.postman_collection.json, pvt-get-single-publisher/index.js
[Trello](https://trello.com/c/nnRJ2aaP)
=> return 404 when no publisher is found with name or id

README.md, postman/schemas/index.yaml
[Trello](https://trello.com/c/EpxezYGN)
=> Add Open API Specification

.github/workflows/develop-func-ci.yml, .github/workflows/develop-func-deploy.yml, .github/workflows/prod-func-deploy.yml, .nvmrc, README.md, database/db.js, integration-tests/validator-services-tests.postman_collection.json, package-lock.json, package.json, postman/schemas/index.yaml, pub-get-stats-summary-aggregate/index.js, pub-get-stats-summary-precalc/index.js
Upgrade to Node 20
Additions to output new advisory field on statistics API endpoints
Add standardised summary table to README
=> Upgrade node.  Add advisory field to stats API endpoints.
